import {
  ecosystemAggressiveDevelopmentLanes,
  ecosystemAiHelperLanes,
  ecosystemSourceActivationPlan,
  ecosystemConnectionAttempts,
  ecosystemConnectionStateSummary,
  ecosystemEnvironmentSourceExports,
  ecosystemInstallPolicySummary,
  ecosystemOutputSurfaces,
  ecosystemPlatformSourceMirror,
  ecosystemPluginInstallPlan,
  ecosystemPluginRefs,
  ecosystemSidePanelReceipts,
  ecosystemSourceDeliveryArtifacts,
  ecosystemSourceExportIndex,
  ecosystemSourceFlatList,
  ecosystemSourceGroups,
  ecosystemSourceKindSummary,
  ecosystemSourceOutputManifest,
  ecosystemSourceProofCards,
  ecosystemSourceReadinessMatrix,
  ecosystemSourceActionBoard,
  ecosystemSourceActionPackets,
  ecosystemSourceQualityGates,
  ecosystemSourceRunbook,
  ecosystemSourceExecutionReceipts,
  ecosystemSourceExecutionDigest,
  ecosystemSourceContinuationBrief,
  ecosystemSourceExecutionQueue,
  ecosystemSourceSignalMap,
  ecosystemSourceTotal,
  polyglotSourceContracts
} from "@seis/content";

export const dynamic = "force-dynamic";

export function GET() {
  return Response.json({
    packageName: "seis-portfolio-plugin-source-package",
    packageVersion: "2026-06-04",
    generatedAt: new Date().toISOString(),
    policy: {
      source: ecosystemSourceOutputManifest.policy,
      sidePanel: ecosystemSourceOutputManifest.platformSidePanelPolicy
    },
    summary: {
      totalSources: ecosystemSourceTotal,
      uniquePluginRefs: ecosystemPluginRefs.length,
      sourceKinds: ecosystemSourceKindSummary,
      connectionStates: ecosystemConnectionStateSummary,
      installPolicies: ecosystemInstallPolicySummary,
      groups: ecosystemSourceGroups.length,
      readinessLanes: ecosystemSourceReadinessMatrix.length,
      activationPlanSteps: ecosystemSourceActivationPlan.length,
      aggressiveDevelopmentLanes: ecosystemAggressiveDevelopmentLanes.length,
      installPlanSteps: ecosystemPluginInstallPlan.length,
      environmentExports: ecosystemEnvironmentSourceExports.length,
      sidePanelReceipts: ecosystemSidePanelReceipts.length,
      platformSourceMirror: ecosystemPlatformSourceMirror.length,
      proofCards: ecosystemSourceProofCards.length,
      sourceActionBoardColumns: ecosystemSourceActionBoard.columns.length,
      sourceActionPackets: ecosystemSourceActionPackets.length,
      sourceQualityGates: ecosystemSourceQualityGates.length,
      sourceRunbookSteps: ecosystemSourceRunbook.steps.length,
      sourceExecutionReceipts: ecosystemSourceExecutionReceipts.length,
      sourceExecutionDigestMetrics: ecosystemSourceExecutionDigest.metrics.length,
      sourceContinuationBriefReadPaths: ecosystemSourceContinuationBrief.readFirstPaths.length,
      sourceExecutionQueue: ecosystemSourceExecutionQueue.length,
      sourceSignalMap: ecosystemSourceSignalMap.length,
      aiHelperLanes: ecosystemAiHelperLanes.length,
      exportIndexItems: ecosystemSourceExportIndex.length,
      deliveryArtifacts: ecosystemSourceDeliveryArtifacts.length,
      outputSurfaces: ecosystemOutputSurfaces.length,
      polyglotContracts: polyglotSourceContracts.length,
      connectionAttempts: ecosystemConnectionAttempts.length
    },
    outputs: ecosystemOutputSurfaces,
    pluginRefs: ecosystemPluginRefs,
    sources: ecosystemSourceFlatList,
    groups: ecosystemSourceGroups,
    readinessMatrix: ecosystemSourceReadinessMatrix,
    activationPlan: ecosystemSourceActivationPlan,
    aggressiveDevelopmentLanes: ecosystemAggressiveDevelopmentLanes,
    installPlan: ecosystemPluginInstallPlan,
    environmentExports: ecosystemEnvironmentSourceExports,
    sidePanelReceipts: ecosystemSidePanelReceipts,
    platformSourceMirror: ecosystemPlatformSourceMirror,
    proofCards: ecosystemSourceProofCards,
    sourceActionBoard: ecosystemSourceActionBoard,
    sourceActionPackets: ecosystemSourceActionPackets,
    sourceQualityGates: ecosystemSourceQualityGates,
    sourceRunbook: ecosystemSourceRunbook,
    sourceExecutionReceipts: ecosystemSourceExecutionReceipts,
    sourceExecutionDigest: ecosystemSourceExecutionDigest,
    sourceContinuationBrief: ecosystemSourceContinuationBrief,
    sourceExecutionQueue: ecosystemSourceExecutionQueue,
    sourceSignalMap: ecosystemSourceSignalMap,
    aiHelperLanes: ecosystemAiHelperLanes,
    exportIndex: ecosystemSourceExportIndex,
    deliveryArtifacts: ecosystemSourceDeliveryArtifacts,
    connectionEvidence: ecosystemConnectionAttempts,
    polyglotContracts: polyglotSourceContracts
  });
}
