10 REM SEIS Release Policy — BASIC
20 REM Motion mode and release gate constants

100 LET CINEMATIC = 0
110 LET BALANCED  = 1
120 LET REDUCED   = 2

200 LET READY   = 0
210 LET BLOCKED = 1
220 LET PENDING = 2

300 REM --- Resolve motion mode ---
310 LET PREFERS_REDUCED = 1
320 LET REQUESTED_MODE  = CINEMATIC

330 IF PREFERS_REDUCED = 1 THEN LET RESOLVED_MODE = REDUCED ELSE LET RESOLVED_MODE = REQUESTED_MODE

400 REM --- Motion duration (ms) ---
410 IF RESOLVED_MODE = CINEMATIC THEN LET DURATION = 600
420 IF RESOLVED_MODE = BALANCED  THEN LET DURATION = 300
430 IF RESOLVED_MODE = REDUCED   THEN LET DURATION = 0

500 REM --- Release gate check ---
510 LET STATUS = READY
520 IF STATUS = READY THEN LET CAN_DEPLOY = 1 ELSE LET CAN_DEPLOY = 0

600 PRINT "Resolved mode: "; RESOLVED_MODE
610 PRINT "Duration ms:   "; DURATION
620 PRINT "Can deploy:    "; CAN_DEPLOY

700 END
