import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

const testDirectory = path.dirname(fileURLToPath(import.meta.url));
const repositoryRoot = path.resolve(testDirectory, "../../..");
const decisionPath = path.join(repositoryRoot, "content/development/seis-public-plugin-wave-3-capability-decision.json");
const generatorPath = path.join(repositoryRoot, "scripts/create-seis-public-plugin-wave-3-capability-decision.mjs");
const sourceManifestPath = path.join(repositoryRoot, "apps/seis-core/data/seis-core-plugin-sources.json");
const marketplacePath = path.join(repositoryRoot, ".agents/plugins/marketplace.json");

test("preserves the Wave 3 decision while resolving the concurrency capability through one curated bundle", () => {
  const result = spawnSync(process.execPath, [generatorPath, "--check"], {
    cwd: repositoryRoot,
    encoding: "utf8",
  });
  assert.equal(result.status, 0, result.stderr);

  const decision = JSON.parse(fs.readFileSync(decisionPath, "utf8"));
  const sourceManifest = JSON.parse(fs.readFileSync(sourceManifestPath, "utf8"));
  const marketplace = JSON.parse(fs.readFileSync(marketplacePath, "utf8"));
  assert.equal(decision.status, "approved-public-local-implementation");
  assert.equal(decision.decision.selectedCapability, "seis-swift-concurrency-audit");
  assert.equal(decision.decision.implementationStarted, true);
  assert.equal(decision.decision.historicalAdditionalDirectCardAddedAtExecution, true);
  assert.equal(decision.implementation.packageExists, true);
  assert.equal(decision.implementation.publicCardExists, false);
  assert.equal(decision.implementation.directMarketplaceCard, false);
  assert.equal(decision.implementation.sourcePath, "plugins/seis-core/seis-swift-concurrency-audit");
  assert.equal(decision.implementation.marketplaceSourcePath, null);
  assert.equal(decision.implementation.distributionBundleId, "seis-application-bundle-06");
  assert.equal(decision.implementation.distributionBundleCardExists, true);
  assert.equal(decision.implementation.distributionBundleMembershipCount, 1);
  assert.equal(decision.implementation.historicalAdditionalDirectCardAddedAtExecution, true);
  assert.equal(decision.preconditions.wave2HandoffStatus, "completed-repository-local-handoff");
  assert.equal(decision.preconditions.wave3ProgramStatus, "in-progress");
  assert.equal(decision.preconditions.wave3ProgramSelectionStatus, "implementation-approved");
  assert.equal(decision.preconditions.wave3ProgramSelectedCapability, "seis-swift-concurrency-audit");
  assert.equal(decision.historicalWave3Distribution.applicationSourcePackageCount, 73);
  assert.equal(decision.historicalWave3Distribution.marketplaceCardCount, 379);
  assert.equal(decision.historicalWave3Distribution.selectedCapabilityHadDirectMarketplaceCard, true);
  assert.equal(decision.historicalWave3Distribution.additionalDirectCardAddedAtExecution, true);
  assert.equal(decision.currentMarketplaceProjection.marketplaceName, "seis-repo");
  assert.equal(decision.currentMarketplaceProjection.marketplaceDisplayName, "SEIS Repo");
  assert.equal(decision.currentMarketplaceProjection.sourceCapabilityInventory.applicationSourcePackageCount, sourceManifest.plugins.length);
  assert.equal(decision.currentMarketplaceProjection.publicCardCount, marketplace.plugins.length);
  assert.equal(decision.currentMarketplaceProjection.publicCardCount, 34);
  assert.equal(decision.currentMarketplaceProjection.canonicalCardCount, 1);
  assert.equal(decision.currentMarketplaceProjection.bundleCardCount, 33);
  assert.equal(decision.currentMarketplaceProjection.applicationBundleCardCount, 6);
  assert.equal(decision.currentMarketplaceProjection.topicBundleCardCount, 27);
  assert.equal(decision.currentMarketplaceProjection.sourceCapabilityInventory.rootSourceModuleCount, 5);
  assert.equal(decision.currentMarketplaceProjection.sourceCapabilityInventory.topicSourcePackageCount, 300);
  assert.equal(decision.currentMarketplaceProjection.sourceCapabilityInventory.retainedSourcePackageCount, 380);
  assert.equal(decision.currentMarketplaceProjection.selectedApplicationCapability.directMarketplaceCardRequired, false);
  assert.equal(decision.currentMarketplaceProjection.selectedApplicationCapability.directMarketplaceCardCount, 0);
  assert.equal(decision.currentMarketplaceProjection.selectedApplicationCapability.bundleId, "seis-application-bundle-06");
  assert.equal(decision.currentMarketplaceProjection.selectedApplicationCapability.bundleCardCount, 1);
  assert.equal(decision.publicBoundary.personalMarketplaceRead, false);
  assert.equal(decision.publicBoundary.personalMarketplaceMutation, false);
  assert.equal(decision.publicBoundary.network, false);
  assert.equal(decision.publicBoundary.externalWrites, false);
  assert.equal(decision.publicBoundary.secrets, false);
  assert.equal(decision.publicBoundary.publicReleaseAllowed, false);
  assert.equal(decision.staticEvidence.classification, "bounded-static-concurrency-signals-only");
  assert.ok(decision.staticEvidence.scannedSwiftFileCount > 0);
  assert.equal(decision.staticEvidence.scannedSwiftFileCount, decision.staticEvidence.discoveredSwiftFileCount);
  assert.equal(decision.staticEvidence.symlinkCount, 0);
  assert.equal(decision.staticEvidence.credentialAssignmentFindingCount, 0);
  assert.equal(decision.staticEvidence.rawSourceReturned, false);
  assert.equal(decision.staticEvidence.sourceFilesCompiled, false);
  assert.ok(decision.staticEvidence.signals.uncheckedSendable.count > 0);
  assert.ok(decision.staticEvidence.signals.sendableDeclaration.count > 0);
  assert.equal(decision.publicBoundary.compilerInvoked, false);
  assert.equal(decision.publicBoundary.nativeRuntimeStarted, false);
  assert.equal(JSON.stringify(decision).includes(repositoryRoot), false);
});
