import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

const testDirectory = path.dirname(fileURLToPath(import.meta.url));
const repositoryRoot = path.resolve(testDirectory, "../../..");
const recordPath = path.join(repositoryRoot, "content/development/seis-public-plugin-continuity-cadence.json");
const generatorPath = path.join(repositoryRoot, "scripts/create-seis-public-plugin-continuity-cadence.mjs");

test("keeps the requested 30-step bootstrap and five 100-step waves evidence-led and public-only", () => {
  const result = spawnSync(process.execPath, [generatorPath, "--check"], {
    cwd: repositoryRoot,
    encoding: "utf8",
  });
  assert.equal(result.status, 0, result.stderr);

  const cadence = JSON.parse(fs.readFileSync(recordPath, "utf8"));
  assert.equal(cadence.status, "active-evidence-led-cadence");
  assert.equal(cadence.cadence.bootstrap.totalSteps, 30);
  assert.equal(cadence.cadence.bootstrap.roundCount, 5);
  assert.equal(cadence.cadence.bootstrap.stepsPerRound, 6);
  assert.equal(cadence.cadence.waveSeries.waveCount, 5);
  assert.equal(cadence.cadence.waveSeries.stepsPerWave, 100);
  assert.equal(cadence.cadence.waveSeries.totalPlannedWaveSteps, 500);
  assert.equal(cadence.cadence.waveSeries.activeWave, 5);
  assert.equal(cadence.cadence.waveSeries.activeWaveState, "wave-5-first-40-steps-completed-step-41-in-progress");
  assert.equal(cadence.waves.length, 5);
  assert.equal(cadence.waves[0].status, "completed");
  assert.equal(cadence.waves[1].status, "completed");
  assert.equal(cadence.waves[2].status, "completed");
  assert.equal(cadence.waves[2].completedSteps, 100);
  assert.deepEqual(cadence.waves[2].inProgressSteps, []);
  assert.equal(cadence.waves[2].priorValidationPath, "content/development/seis-public-plugin-wave-3-final-validation.json");
  assert.equal(cadence.waves[2].preflightPath, "content/development/seis-public-plugin-wave-3-final-preflight.json");
  assert.equal(cadence.waves[2].deliveryEvidencePath, "content/development/seis-public-plugin-wave-3-delivery-evidence.json");
  assert.equal(cadence.waves[2].repositoryLocalHandoffPath, "content/development/seis-public-plugin-wave-3-repository-local-handoff.json");
  assert.equal(cadence.waves[2].followingWaveReviewPath, "content/development/seis-public-plugin-wave-3-following-wave-review.json");
  assert.equal(cadence.waves[2].closeoutPath, "content/development/seis-public-plugin-wave-3-closeout.json");
  assert.equal(cadence.waves[2].currentEvidencePath, "content/development/seis-public-plugin-wave-3-closeout.json");
  assert.equal(cadence.waves[3].status, "completed");
  assert.equal(cadence.waves[3].programPath, "content/development/seis-public-plugin-wave-4-program.json");
  assert.equal(cadence.waves[3].activationDecisionPath, "content/development/seis-public-plugin-wave-4-activation-decision.json");
  assert.equal(cadence.waves[3].selectedCapability, "seis-swift-package-topology");
  assert.equal(cadence.waves[3].activationApproved, true);
  assert.equal(cadence.waves[3].implementationStarted, true);
  assert.equal(cadence.waves[3].candidatePackageExists, true);
  assert.equal(cadence.waves[3].candidatePublicCardExists, true);
  assert.equal(cadence.waves[3].completedSteps, 100);
  assert.deepEqual(cadence.waves[3].inProgressSteps, []);
  assert.equal(cadence.waves[3].topologyEvidencePath, "content/development/seis-swift-package-topology.json");
  assert.equal(cadence.waves[3].integrationCheckpointPath, "content/development/seis-public-plugin-wave-4-integration-checkpoint.json");
  assert.equal(cadence.waves[3].validationDeliveryEvidencePath, "content/development/seis-public-plugin-wave-4-validation-delivery-evidence.json");
  assert.equal(cadence.waves[3].publicBoundaryDecisionPath, "content/development/seis-public-plugin-wave-4-public-boundary-decision.json");
  assert.equal(cadence.waves[3].handoffPreparationPath, "content/development/seis-public-plugin-wave-4-handoff-preparation.json");
  assert.equal(cadence.waves[3].closeoutSequenceDecisionPath, "content/development/seis-public-plugin-wave-4-closeout-sequence-decision.json");
  assert.equal(cadence.waves[3].repositoryLocalHandoffPath, "content/development/seis-public-plugin-wave-4-repository-local-handoff.json");
  assert.equal(cadence.waves[3].followingWaveReviewPath, "content/development/seis-public-plugin-wave-4-following-wave-review.json");
  assert.equal(cadence.waves[3].evidenceRetentionPath, "content/development/seis-public-plugin-wave-4-evidence-retention.json");
  assert.equal(cadence.waves[3].closeoutPath, "content/development/seis-public-plugin-wave-4-closeout.json");
  assert.equal(cadence.waves[3].currentEvidencePath, "content/development/seis-public-plugin-wave-4-closeout.json");
  assert.equal(cadence.waves[4].status, "in-progress");
  assert.equal(cadence.waves[4].programPath, "content/development/seis-public-plugin-wave-5-program.json");
  assert.equal(cadence.waves[4].candidateReviewPath, "content/development/seis-public-plugin-wave-4-following-wave-review.json");
  assert.equal(cadence.waves[4].activationDecisionPath, "content/development/seis-public-plugin-wave-5-activation-decision.json");
  assert.equal(cadence.waves[4].capabilityEvidencePath, "content/development/seis-plugin-capability-coverage.json");
  assert.equal(cadence.waves[4].selectedCapability, "seis-plugin-capability-coverage");
  assert.equal(cadence.waves[4].implementationApproved, true);
  assert.equal(cadence.waves[4].activationApproved, true);
  assert.equal(cadence.waves[4].implementationStarted, true);
  assert.equal(cadence.waves[4].candidatePackageExists, true);
  assert.equal(cadence.waves[4].candidatePublicCardExists, true);
  assert.equal(cadence.waves[4].completedSteps, 40);
  assert.deepEqual(cadence.waves[4].inProgressSteps, [41]);
  assert.equal(cadence.waves[4].currentEvidencePath, "content/development/seis-plugin-capability-coverage.json");
  assert.equal(cadence.futureWaveTemplate.steps.length, 100);
  assert.equal(cadence.executionBoundary.personalMarketplaceRead, false);
  assert.equal(cadence.executionBoundary.personalMarketplaceMutation, false);
  assert.equal(cadence.executionBoundary.backgroundExecutionClaimed, false);
  assert.equal(cadence.executionBoundary.protectedDefaultBranchWrites, false);
  assert.equal(JSON.stringify(cadence).includes(repositoryRoot), false);
});
