import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

const testDirectory = path.dirname(fileURLToPath(import.meta.url));
const repositoryRoot = path.resolve(testDirectory, "../../..");
const programPath = path.join(repositoryRoot, "content/development/seis-public-plugin-wave-4-program.json");
const generatorPath = path.join(repositoryRoot, "scripts/create-seis-public-plugin-wave-4-program.mjs");

test("completes Wave 4 locally while keeping Wave 5 planned-gated", () => {
  const result = spawnSync(process.execPath, [generatorPath, "--check"], {
    cwd: repositoryRoot,
    encoding: "utf8",
  });
  assert.equal(result.status, 0, result.stderr);

  const program = JSON.parse(fs.readFileSync(programPath, "utf8"));
  assert.equal(program.schemaVersion, 2);
  assert.equal(program.status, "completed");
  assertCurrentAndHistoricalMarketplaceSemantics(program);
  assert.equal(program.maturity, "prototype");
  assert.equal(program.wave.number, 4);
  assert.equal(program.wave.totalSteps, 100);
  assert.equal(program.rounds.length, 5);
  assert.equal(program.steps.length, 100);
  assert.ok(program.steps.every((step, index) => step.number === index + 1 && step.status === "completed"));
  assert.equal(program.scope.selectedCapability, "seis-swift-package-topology");
  assert.equal(program.activationGate.status, "implemented-repository-local");
  assert.equal(program.activationGate.activationDecisionPath, "content/development/seis-public-plugin-wave-4-activation-decision.json");
  assert.equal(program.activationGate.implementationStarted, true);
  assert.equal(program.activationGate.candidatePackageExists, true);
  assert.equal(program.activationGate.candidatePublicCardExists, true);
  assert.deepEqual(program.progress.inProgressStepNumbers, []);
  assert.equal(program.progress.completedStepCount, 100);
  assert.equal(program.progress.completedRoundCount, 5);
  assert.equal(program.progress.plannedStepCount, 0);
  assert.equal(program.progress.nextStepNumber, null);
  assert.equal(program.evidence.integrationCheckpointPath, "content/development/seis-public-plugin-wave-4-integration-checkpoint.json");
  assert.equal(program.evidence.validationDeliveryEvidencePath, "content/development/seis-public-plugin-wave-4-validation-delivery-evidence.json");
  assert.equal(program.evidence.publicBoundaryDecisionPath, "content/development/seis-public-plugin-wave-4-public-boundary-decision.json");
  assert.equal(program.evidence.handoffPreparationPath, "content/development/seis-public-plugin-wave-4-handoff-preparation.json");
  assert.equal(program.evidence.closeoutSequenceDecisionPath, "content/development/seis-public-plugin-wave-4-closeout-sequence-decision.json");
  assert.equal(program.closeoutSequence.status, "completed-repository-local-wave-closeout");
  assert.equal(program.closeoutSequence.approvalSource, "active-thread-user-continuation-objective");
  assert.deepEqual(program.closeoutSequence.completedSteps, [96, 97, 98, 99, 100]);
  assert.equal(program.closeoutSequence.activeStep, null);
  assert.equal(program.closeoutSequence.terminalHandoffPublished, false);
  assert.equal(program.closeoutSequence.waveCompleted, true);
  assert.equal(program.closeoutSequence.wave5ActivationApproved, false);
  assert.equal(program.closeoutSequence.completionEvidencePath, "content/development/seis-public-plugin-wave-4-closeout.json");
  assert.equal(program.evidence.repositoryLocalHandoffPath, "content/development/seis-public-plugin-wave-4-repository-local-handoff.json");
  assert.equal(program.repositoryLocalHandoff.status, "completed-repository-local-handoff");
  assert.equal(program.repositoryLocalHandoff.completedStep, 97);
  assert.equal(program.repositoryLocalHandoff.activeStep, 98);
  assert.equal(program.repositoryLocalHandoff.terminalHandoffPublished, false);
  assert.equal(program.repositoryLocalHandoff.waveCompleted, false);
  assert.equal(program.repositoryLocalHandoff.wave5ActivationApproved, false);
  assert.equal(program.evidence.wave4FollowingWaveReviewPath, "content/development/seis-public-plugin-wave-4-following-wave-review.json");
  assert.equal(program.followingWaveReview.status, "completed-following-wave-scope-review");
  assert.equal(program.followingWaveReview.reviewPath, "content/development/seis-public-plugin-wave-4-following-wave-review.json");
  assert.equal(program.followingWaveReview.completedStep, 98);
  assert.equal(program.followingWaveReview.activeStep, 99);
  assert.equal(program.followingWaveReview.selectedWave5Capability, "seis-plugin-capability-coverage");
  assert.equal(program.followingWaveReview.wave5ImplementationApproved, false);
  assert.equal(program.followingWaveReview.wave5ActivationApproved, false);
  assert.equal(program.evidence.evidenceRetentionPath, "content/development/seis-public-plugin-wave-4-evidence-retention.json");
  assert.equal(program.evidenceRetention.status, "completed-public-evidence-retention");
  assert.equal(program.evidenceRetention.retentionPath, "content/development/seis-public-plugin-wave-4-evidence-retention.json");
  assert.equal(program.evidenceRetention.completedStep, 99);
  assert.equal(program.evidenceRetention.activeStep, 100);
  assert.equal(program.evidenceRetention.deletionPerformed, false);
  assert.equal(program.evidenceRetention.externalStorageUsed, false);
  assert.equal(program.evidenceRetention.wave5ImplementationApproved, false);
  assert.equal(program.evidenceRetention.wave5ActivationApproved, false);
  assert.equal(program.evidence.closeoutPath, "content/development/seis-public-plugin-wave-4-closeout.json");
  assert.equal(program.repositoryLocalCloseout.status, "completed-repository-local-wave-closeout");
  assert.equal(program.repositoryLocalCloseout.closeoutPath, "content/development/seis-public-plugin-wave-4-closeout.json");
  assert.equal(program.repositoryLocalCloseout.completedStep, 100);
  assert.equal(program.repositoryLocalCloseout.nextActiveWave, null);
  assert.equal(program.repositoryLocalCloseout.nextWaveStatus, "planned-gated");
  assert.equal(program.repositoryLocalCloseout.nextWaveSelectedCapability, "seis-plugin-capability-coverage");
  assert.equal(program.repositoryLocalCloseout.nextWaveImplementationApproved, false);
  assert.equal(program.repositoryLocalCloseout.nextWaveActivationApproved, false);
  assert.equal(program.repositoryLocalCloseout.terminalHandoffPublished, false);
  assert.equal(program.repositoryLocalCloseout.publicReleaseAllowed, false);
  assert.ok(Object.values(program.checks).every(Boolean));
  assert.equal(program.publicBoundary.marketplaceName, "seis-repo");
  assert.equal(program.publicBoundary.personalMarketplaceRead, false);
  assert.equal(program.publicBoundary.personalMarketplaceMutation, false);
  assert.equal(program.publicBoundary.network, false);
  assert.equal(program.publicBoundary.externalWrites, false);
  assert.equal(program.publicBoundary.secrets, false);
  assert.equal(program.externalClaims.compiledSwift, false);
  assert.equal(program.externalClaims.swiftPmTestPass, false);
  assert.equal(program.externalClaims.publicRelease, false);
  assert.equal(JSON.stringify(program).includes(repositoryRoot), false);
});

function assertCurrentAndHistoricalMarketplaceSemantics(record) {
  assert.equal(record.historicalWave4DirectCardSnapshot.projectionModel, "direct-source-cards");
  assert.equal(record.historicalWave4DirectCardSnapshot.publicCardCount, 380);
  assert.equal(record.historicalWave4DirectCardSnapshot.retainedSourceCapabilityCount, 379);
  assert.equal(record.historicalWave4DirectCardSnapshot.current, false);
  assert.equal(record.historicalWave4DirectCardSnapshot.immutableHistoricalEvidence, true);
  assert.equal(record.currentMarketplaceProjection.publicCardCount, 34);
  assert.notEqual(record.currentMarketplaceProjection.publicCardCount, 380);
  assert.notEqual(record.currentMarketplaceProjection.publicCardCount, 381);
  assert.equal(record.currentMarketplaceProjection.canonicalCardCount, 1);
  assert.equal(record.currentMarketplaceProjection.bundleCardCount, 33);
  assert.equal(record.currentMarketplaceProjection.applicationBundleCardCount, 6);
  assert.equal(record.currentMarketplaceProjection.topicBundleCardCount, 27);
  assert.equal(record.currentMarketplaceProjection.sourceCapabilityInventory.rootSourceModuleCount, 5);
  assert.equal(record.currentMarketplaceProjection.sourceCapabilityInventory.applicationSourcePackageCount, 75);
  assert.equal(record.currentMarketplaceProjection.sourceCapabilityInventory.topicSourcePackageCount, 300);
  assert.equal(record.currentMarketplaceProjection.sourceCapabilityInventory.retainedSourcePackageCount, 380);
  assert.equal(record.currentMarketplaceProjection.directSourceCapabilityCardCount, 0);
}
