import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

const testDirectory = path.dirname(fileURLToPath(import.meta.url));
const repositoryRoot = path.resolve(testDirectory, "../../..");
const evidencePath = path.join(repositoryRoot, "content/development/seis-swift-concurrency-audit.json");
const generatorPath = path.join(repositoryRoot, "scripts/create-seis-swift-concurrency-audit.mjs");

test("reconciles bounded Swift concurrency evidence with the public SEIS Repo contract", () => {
  const result = spawnSync(process.execPath, [generatorPath, "--check"], {
    cwd: repositoryRoot,
    encoding: "utf8",
  });
  assert.equal(result.status, 0, result.stderr);

  const evidence = JSON.parse(fs.readFileSync(evidencePath, "utf8"));
  assert.equal(evidence.id, "seis-swift-concurrency-audit");
  assert.equal(evidence.goalId, "SEIS-GOAL-021");
  assert.equal(evidence.status, "attention-public-static-concurrency-evidence");
  assert.equal(evidence.plugin.marketplaceName, "seis-repo");
  assert.equal(evidence.plugin.marketplaceDisplayName, "SEIS Repo");
  assert.equal(evidence.plugin.publicAudience, "everyone");
  assert.equal(evidence.plugin.publicMarketplace, true);
  assert.equal(evidence.plugin.directMarketplaceCard, false);
  assert.equal(evidence.plugin.distributionBundleId, "seis-application-bundle-06");
  assert.equal(evidence.plugin.distributionBundleMembershipCount, 1);
  assert.deepEqual(evidence.marketplace, evidence.currentMarketplaceProjection);
  assert.equal(evidence.currentMarketplaceProjection.projectionModel, "curated-bundle-cards");
  assert.equal(evidence.currentMarketplaceProjection.publicCardCount, 34);
  assert.equal(evidence.currentMarketplaceProjection.canonicalCardCount, 1);
  assert.equal(evidence.currentMarketplaceProjection.bundleCardCount, 33);
  assert.equal(evidence.currentMarketplaceProjection.applicationBundleCardCount, 6);
  assert.equal(evidence.currentMarketplaceProjection.topicBundleCardCount, 27);
  assert.equal(evidence.currentMarketplaceProjection.directSourceCapabilityCardCount, 0);
  assert.equal(evidence.currentMarketplaceProjection.sourceCapabilityInventory.rootSourceModuleCount, 5);
  assert.equal(evidence.currentMarketplaceProjection.sourceCapabilityInventory.applicationSourcePackageCount, 75);
  assert.equal(evidence.currentMarketplaceProjection.sourceCapabilityInventory.topicSourcePackageCount, 300);
  assert.equal(evidence.currentMarketplaceProjection.sourceCapabilityInventory.retainedSourcePackageCount, 380);
  assert.equal(evidence.currentMarketplaceProjection.selectedApplicationCapability.directMarketplaceCardRequired, false);
  assert.equal(evidence.currentMarketplaceProjection.selectedApplicationCapability.directMarketplaceCardCount, 0);
  assert.equal(evidence.currentMarketplaceProjection.selectedApplicationCapability.bundleId, "seis-application-bundle-06");
  assert.equal(evidence.currentMarketplaceProjection.selectedApplicationCapability.bundleCardCount, 1);
  assert.equal(evidence.historicalWave3Snapshot.classification, "immutable-wave-3-direct-card-evidence-snapshot");
  assert.equal(evidence.historicalWave3Snapshot.applicationSourcePackageCount, 73);
  assert.equal(evidence.historicalWave3Snapshot.directApplicationCardCount, 73);
  assert.equal(evidence.historicalWave3Snapshot.publicCardCount, 379);
  assert.equal(evidence.historicalWave3Snapshot.selectedCapabilityHadDirectMarketplaceCard, true);
  assert.equal(evidence.historicalWave3Snapshot.additionalDirectCardAddedAtExecution, true);
  assert.equal(evidence.historicalWave3Snapshot.current, false);
  assert.equal(evidence.historicalWave3Snapshot.immutableHistoricalEvidence, true);
  assert.equal(evidence.decision.selectedCapability, "seis-swift-concurrency-audit");
  assert.equal(evidence.decision.implementationStarted, true);
  assert.equal(evidence.decision.historicalAdditionalDirectCardAddedAtExecution, true);
  assert.equal(evidence.decision.currentDirectMarketplaceCard, false);
  assert.equal(evidence.decision.currentDistributionBundleId, "seis-application-bundle-06");
  assert.equal(evidence.decision.currentDistributionBundleMembershipCount, 1);
  assert.equal(evidence.audit.state, "attention");
  assert.equal(evidence.audit.ok, true);
  assert.equal(evidence.audit.classification, "bounded-static-concurrency-signals-only");
  assert.equal(evidence.audit.blockingFindingCount, 0);
  assert.ok(evidence.audit.scannedSwiftFileCount > 0);
  assert.ok(evidence.audit.findingCodes.includes("unchecked-sendable-review-required"));
  assert.equal(evidence.safety.write.length, 0);
  assert.equal(evidence.safety.network.length, 0);
  assert.equal(evidence.safety.secrets.length, 0);
  assert.equal(evidence.safety.compilesSwift, false);
  assert.equal(evidence.safety.runsSwiftTests, false);
  assert.equal(evidence.safety.startsNativeApplication, false);
  assert.equal(evidence.safety.publicReleaseAllowed, false);
  assert.equal(evidence.inputSafety.credentialAssignmentFindingCount, 0);
  assert.equal(evidence.inputSafety.rawSourceReturned, false);
  assert.equal(evidence.inputSafety.rawMatchedValuesReturned, false);
  assert.equal(evidence.inputSafety.sourceFilesCompiled, false);
  assert.equal(evidence.publicBoundary.personalMarketplaceRead, false);
  assert.equal(evidence.publicBoundary.personalMarketplaceMutation, false);
  assert.equal(evidence.publicBoundary.network, false);
  assert.equal(evidence.publicBoundary.externalWrites, false);
  assert.equal(evidence.publicBoundary.secrets, false);
  assert.equal(evidence.publicBoundary.publicReleaseAllowed, false);
  assert.equal(JSON.stringify(evidence).includes(repositoryRoot), false);
});
